config/routes.rb
Rails.application.routes.draw do
  # Back admin routes start


  namespace :owner do
    root to: 'subscriptions#index'
    resources :students
    resources :asignatures
    resources :subscriptions
    resources :fees
    get '/dashboard', to: 'dashboard#index'
    get '/generate_fees/:month/:year', to: 'fees#generate_fees', as: 'generate_fees'
    get '/pay_fee/:id/:fee_id', to: 'fees#pay_fee', as: 'pay_fee'
  end

  namespace :admin do
    root to: 'dashboard#index'
    resources :users
    resources :institutions
    get '/send_promotion_email', to: 'dashboard#send_promotion_email', as: 'send_promotion_email'
    get '/edit_password/:id', to: 'users#edit_password', as: 'user_edit_password'
  end

  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  # Application root
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # Front routes end
end

app/models/asignature.rb
class Asignature < ApplicationRecord
  belongs_to :institution
end

app/controllers/owner/asignatures_controller.rb
module Owner
  class AsignaturesController < Owner::BaseController
    before_action :set_asignature, only: [:show, :edit, :update, :destroy]
    before_action :set_institution, only: [:create]

    # GET /asignatures
    def index
      @asignatures = Asignature.all
    end

    # GET /asignatures/1
    def show
    end

    # GET /asignatures/new
    def new
      @asignature = Asignature.new
      @url = owner_asignatures_path
    end

    # GET /asignatures/1/edit
    def edit
      @url = owner_asignature_path(@asignature)
    end

    # POST /asignatures
    def create
      @asignature = Asignature.new(asignature_params)
      @asignature.institution = @institution

      respond_to do |format|
        if @asignature.save
          format.html { redirect_to owner_asignatures_path, notice: t('owner.asignatures.create.success') }
        else
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /asignatures/1
    def update
      respond_to do |format|
        if @asignature.update(asignature_params)
          format.html { redirect_to owner_asignatures_path, notice: t('owner.asignatures.update.success') }
        else
          format.html { render :edit }
        end
      end
    end

    # DELETE /asignatures/1
    def destroy
      @asignature.destroy
      respond_to do |format|
        format.html { redirect_to owner_asignatures_url, notice: t('owner.asignatures.destroy.success') }
      end
    end

    private
      def set_asignature
        @asignature = Asignature.find(params[:id])
      end

      def set_institution
        @institution = current_user.institution_owner.institution
      end

      def asignature_params
        params.require(:asignature).permit(:name)
      end
  end
end

app/controllers/owner/base_controller.rb
module Owner
  class BaseController < ApplicationController
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    before_action :verify_institution_owner

    layout :layout_by_resource

    def index
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:password, :password_confirmation, :current_password, :name, roles: [])
      end
    end

    private 
    
      def layout_by_resource
        if devise_controller?
          'layouts/devise'
        else
          'admin/layouts/admin'
        end
      end
      
      def verify_institution_owner
        raise CanCan::AccessDenied unless current_user.is?(:institution_owner)
      end
  end
end

app/controllers/owner/dashboard_controller.rb
include ActionView::Helpers::NumberHelper

module Owner
    class DashboardController < Owner::BaseController
  
      # GET /dashboard
      def index
        @active_suscriptions = Subscription.actives.count
        @current_year = Time.now.year
        @current_month = Time.now.month
        @generated_items_fees_count = Item.joins(:fee).where("fees.month = #{@current_month}").count
        @total_payed = Fee.where(month: @current_month).payed.count
        if @generated_items_fees_count > 0
          @fee_payed_percentaje = number_with_precision((@total_payed.to_f / @generated_items_fees_count.to_f) * 100, :precision => 2)
        else
          @fee_payed_percentaje = 0
        end


      end

      
  
  end
end

app/controllers/owner/fees_controller.rb
module Owner
    class FeesController < Owner::BaseController
      before_action :set_fee, only: [:show, :edit, :update, :destroy, :pay_fee]
      before_action :set_institution, only: [:index, :create]
  
      # GET /fees/1
      def show
      end
  
      # GET /fees/1/edit
      def edit
        @url = owner_fee_path(@fee)
      end
  
      # PATCH/PUT /fees/1
      def update
        respond_to do |format|
          if @fee.update(fee_params)
            format.html { redirect_to owner_subscriptions_path, notice: t('owner.fees.update.success') }
          else
            @url = owner_fees_path
            flash[:warning] = @fee.errors.full_messages.uniq.join(', ')
            format.html { render :edit }
          end
        end
      end
  
      # DELETE /fees/1
      def destroy
        @fee.destroy
        
        respond_to do |format|
          format.html { redirect_to owner_fees_url, notice: t('owner.fees.destroy.success') }
        end
      end

      def generate_fees
        month = params[:month]
        year = params[:year]

        generated_count = 0
        Student.actives.each do |student|
          if student.fees.where(month: month).empty?
            
            fee = student.fees.create!(
              year: year,
              month: month,
              amount_paid: 0,
              status: 0
            )

            total_to_pay = 0
            subscriptions = 
              student.subscriptions
                .where(status: 1)

            subscriptions.each do |subscription|
              total_to_pay += subscription.price
              fee.items.create!(
                asignature_name: subscription.asignature.name,
                subscription_price: subscription.price,
                day: subscription.day.name,
                start_at: subscription.start_at.str_time,
                end_at: subscription.end_at.str_time,
                classroom: subscription.classroom.name
              )
              generated_count += 1
            end

            fee.total_to_pay = total_to_pay
            fee.save
          end
        end

        respond_to do |format|
          format.html { redirect_to owner_dashboard_url, notice: "Se han generado #{generated_count} coutas satisfactoriamente." }
        end

      end
  
      def pay_fee
        fee = Fee.find(params[:fee_id])
  
        fee.payed!
        fee.amount_paid = fee.total_to_pay
        fee.save
  
        fee.student.contact_informations.each do |contact|
          StudentMailer.receipt_email(fee, contact.email).deliver_now
        end
  
        StudentMailer.receipt_email(fee, "axeltaglia@gmail.com").deliver_now
        StudentMailer.receipt_email(fee, "sennhauserc@gmail.com").deliver_now
        
        respond_to do |format|
          format.html { redirect_to owner_student_path(fee.student), notice: "El recibo fue generado y enviado exitosamente." }
        end
      end
  
      private
        def set_fee
          @fee = Fee.find(params[:id])
        end
  
        def set_institution
          @institution = current_user.institution_owner.institution
        end
  
        def fee_params
          params.require(:fee).permit(
            :total_to_pay, 
            :amount_paid, 
            :status
          )
        end
    end
  end

app/controllers/owner/students_controller.rb
module Owner
  class StudentsController < Owner::BaseController
    before_action :set_student, only: [:show, :edit, :update, :destroy, :pay_fee]
    before_action :set_institution, only: [:index, :create]

    # GET /students
    def index
      @students = @institution.students.all
    end

    # GET /students/1
    def show
    end

    # GET /students/new
    def new
      @student = Student.new
      @url = owner_students_path
      @student.contact_informations.build
      @student.subscriptions.build
    end

    # GET /students/1/edit
    def edit
      @url = owner_student_path(@student)
    end

    # POST /students
    def create
      @student = Student.new(student_params)
      @student.institution = @institution
      email = @student.contact_informations.first.email

      respond_to do |format|
        if @student.save
          @student.save
          format.html { redirect_to owner_subscriptions_path, notice: t('owner.students.create.success') }
        else
          @url = owner_students_path
          flash[:warning] = @student.errors.full_messages.uniq.join(', ')
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /students/1
    def update
      respond_to do |format|
        if @student.update(student_params)
          format.html { redirect_to owner_subscriptions_path, notice: t('owner.students.update.success') }
        else
          @url = owner_students_path
          flash[:warning] = @student.errors.full_messages.uniq.join(', ')
          format.html { render :edit }
        end
      end
    end

    # DELETE /students/1
    def destroy
      @student.subscriptions.destroy_all
      @student.contact_informations.destroy_all
      @student.destroy
      
      respond_to do |format|
        format.html { redirect_to owner_students_url, notice: t('owner.students.destroy.success') }
      end
    end

    private
      def set_student
        @student = Student.find(params[:id])
      end

      def set_institution
        @institution = current_user.institution_owner.institution
      end

      def student_params
        params.require(:student).permit(
          :name, 
          :last_name, 
          :email, 
          :phone, 
          :description, 
          :status, 
          contact_informations_attributes:[
            :email, 
            :phone, 
            :description, 
            :receives_emails, 
            :_destroy, 
            :id
          ],
          subscriptions_attributes:[
            :asignature_id, 
            :status, 
            :day_id, 
            :start_at_id, 
            :end_at_id, 
            :classroom_id,
            :price, 
            :_destroy, 
            :id
          ], 
          
        )
      end
  end
end

app/controllers/owner/subscriptions_controller.rb
module Owner
    class SubscriptionsController < Owner::BaseController
      before_action :set_student, only: [:show, :edit, :update, :destroy, :pay_fee]
      before_action :set_institution, only: [:index, :create]
  
      # GET /subscriptions
      def index
        @subscriptions = 
            Subscription
              .where(status: 1)
              .includes(:day)
              .includes(:start_at)
              .includes(:student)
              .order('students.name', 'students.last_name')

      end
      
      private
        def set_student
          @student = Student.find(params[:id])
        end
  
        def set_institution
          @institution = current_user.institution_owner.institution
        end
  
    end
  end

app/views/owner/asignatures/_form.html.erb
<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control", required: true %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

app/views/owner/asignatures/edit.html.erb
<%= form_for @asignature, url: @url, role: :form do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="box-title"><%= t('owner.asignatures.edit.title') %></h3>
        </div>

        <div class="panel-body">
          <%= render partial: 'owner/asignatures/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to t('button.cancel'), owner_asignatures_path, class: 'btn btn-danger' %>
          <%= f.submit t('button.submit'), class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/owner/asignatures/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">

      <div class="panel-heading">
      <h3 class="box-title"><%= t('owner.asignatures.index.title') %></h3>
      </div>

      <div class="panel-body">
        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <th><%= t('activerecord.attributes.asignatures.name') %></th>
              <th><%= t('form.column.actions') %></th>
            </tr>
          </thead>

          <tbody>
            <% @asignatures.each do |asignature| %>
            <tr>
              <td> 
                <%= link_to owner_asignature_path(asignature) do %> 
                <%= asignature.name %> 
                <% end %>
              </td>
              <td>
                <div class="btn-row">
                  <%= link_to raw('<i class="fa fa-eye"></i>'), owner_asignature_path(asignature), class: 'btn btn-sm btn-success' %>
                  <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_owner_asignature_path(asignature), class: 'btn btn-sm btn-warning' %>
                  <%= link_to raw('<i class="fa fa-trash"></i>'), owner_asignature_path(asignature), class: 'btn btn-sm btn-danger', method: :delete,
                  data: { confirm: t('owner.asignatures.destroy.warning') } %>
                </div>
              </td>
            </tr>
            <% end %>
          </tbody>

          <tfoot>
            <tr role="row">
              <th><%= t('activerecord.attributes.asignatures.name') %></th>
              <th><%= t('form.column.actions') %></th>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to t('button.new'), new_owner_asignature_path, class: 'btn btn-success pull-right' %>
  </div>
</div>

app/views/owner/asignatures/new.html.erb
<%= form_for @asignature, url: @url, role: :form do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="box-title"><%= t('owner.asignatures.new.title') %></h3>
        </div>

        <div class="panel-body">
          <%= render partial: 'owner/asignatures/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to t('button.cancel'), owner_asignatures_path, class: 'btn btn-danger' %>
          <%= f.submit t('button.submit'), class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/owner/asignatures/show.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-default">

			<div class="panel-heading">
				<h3 class="box-title"><%= t('owner.asignatures.show.title') %></h3>
			</div>

			<div class="panel-body">
				<p>
					<strong><%= t('activerecord.attributes.asignatures.name') %>:</strong>
					<%= @asignature.name %>
				</p>

				<%= link_to raw('<i class="fa fa-pencil"></i>'), edit_owner_asignature_url(@asignature), class: 'btn btn-sm btn-warning' %>

				<%= link_to raw('<i class="fa fa-trash"></i>'), owner_asignature_url(@asignature), class: 'btn btn-sm btn-danger', method: :delete,
                                            data: { confirm: t('owner.asignatures.destroy.warning')} %>
			</div>

			<div class="box-footer">
				<%= link_to t('button.back'), owner_asignatures_path, class: 'btn btn-success' %>
			</div>

		</div>
	</div>
</div>