config/routes.rb
Rails.application.routes.draw do
  # Back admin routes start


  namespace :owner do
    root to: 'subscriptions#index'
    resources :students
    resources :asignatures
    resources :subscriptions
    resources :fees
    get '/dashboard', to: 'dashboard#index'
    get '/generate_fees/:month/:year', to: 'fees#generate_fees', as: 'generate_fees'
    get '/pay_fee/:id/:fee_id', to: 'fees#pay_fee', as: 'pay_fee'
  end

  namespace :admin do
    root to: 'dashboard#index'
    resources :users
    resources :institutions
    get '/send_promotion_email', to: 'dashboard#send_promotion_email', as: 'send_promotion_email'
    get '/edit_password/:id', to: 'users#edit_password', as: 'user_edit_password'
  end

  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  # Application root
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # Front routes end
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :institution_owners
  has_many :students, dependent: :delete_all
  
  validates :name, presence: true
end

app/controllers/admin/institutions_controller.rb
module Admin
  class InstitutionsController < Admin::BaseController
    before_action :set_institution, only: [:show, :edit, :update, :destroy]

    # GET /institutions
    def index
      @institutions = Institution.all
    end

    # GET /institutions/1
    def show
    end

    # GET /institutions/new
    def new
      @institution = Institution.new
      @url = admin_institutions_path
    end

    # GET /institutions/1/edit
    def edit
      @url = admin_institution_path(@institution)
    end

    # POST /institutions
    def create
      @institution = Institution.new(institution_params)

      respond_to do |format|
        if @institution.save
          format.html { redirect_to admin_institutions_path, notice: t('admin.institutions.create.success') }
        else
          @url = admin_institutions_path
          flash[:warning] = @institution.errors.full_messages.uniq.join(', ')
          format.html { render :new }
        end
      end
    end

    # PATCH/PUT /institutions/1
    def update
      respond_to do |format|
        if @institution.update(institution_params)
          format.html { redirect_to admin_institutions_path, notice: t('admin.institutions.update.success') }
        else
          @url = admin_institution_path(@institution)
          flash[:warning] = @institution.errors.full_messages.uniq.join(', ')
          format.html { render :edit }
        end
      end
    end

    # DELETE /institutions/1
    def destroy
    InstitutionsService.new.destroy_institution(@institution)
      respond_to do |format|
        format.html { redirect_to admin_institutions_url, notice: t('admin.institutions.destroy.success') }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_institution
        @institution = Institution.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def institution_params
        params.require(:institution).permit(:name, :institution_owner_id)
      end
  end
end

app/controllers/institution/base_controller.rb
module Institution
  class BaseController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    before_action :verify_institution_owner

    layout :layout_by_resource

    def index
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:password, :password_confirmation, :current_password, :name, roles: [])
      end
    end

    private 
    
      def layout_by_resource
        if devise_controller?
          'layouts/devise'
        else
          'admin/layouts/admin'
        end
      end
      
      def verify_institution_owner
        raise CanCan::AccessDenied unless current_user.is?(:institution_owner)
      end
  end
end

app/controllers/institution/dashboard_controller.rb
module Institution
    class DashboardController < Institution::BaseController
      respond_to :json, :html
  
      # GET /dashboard
      # GET /dashboard.json
      def index
      end
  
  end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/admin/institutions/_form.html.erb
<div class="form-group">
  <%= f.label t('activerecord.attributes.institution.name') %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter name" %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

<div class="form-group">
  <%= f.label t('activerecord.attributes.institution.institution_owner') %>
  <%# collection_select(:institution, :institution_owner_id, InstitutionOwner.all, :id, :email, {:include_blank => true}, {:class => 'form-control'} ) %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

app/views/admin/institutions/edit.html.erb
<%= form_for @institution, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="box-title"><%= t('admin.institutions.edit.title') %></h3>
        </div>

        <div class="panel-body">
          <%= render partial: 'admin/institutions/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to t('button.cancel'), admin_institutions_path, class: 'btn btn-danger' %>
          <%= f.submit t('button.submit'), class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/institutions/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h3 class="panel-title"><%= t('admin.institutions.index.title') %></h3>
      </div>

      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-striped">
            <thead>
              <tr>
                <th><%= t('activerecord.attributes.institutions.name') %></th>
                <th><%= t('activerecord.attributes.institutions.institution_owner') %></th>
                <th class="col-xs-1"><%= t('table.column.actions') %></th></th>
              </tr>
            </thead>

            <tbody>
              <% @institutions.each do |institution| %>
              <tr>
                <td> 
                  <%= link_to edit_admin_institution_url(institution) do %> 
                  <%= institution.name %>
                  <% end %>  
                </td>
                <td> <%# institution.institution_owner.user.name %> </td>
                <td>
                  <div class="btn-row">
                    <%= link_to raw('<i class="fa fa-eye"></i>'), admin_institution_url(institution), class: 'btn btn-sm btn-success' %>
                    <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_admin_institution_url(institution), class: 'btn btn-sm btn-warning' %>
                    <%= link_to raw('<i class="fa fa-trash"></i>'), admin_institution_url(institution), class: 'btn btn-sm btn-danger', method: :delete,
                    data: { confirm: t('admin.institutions.destroy.warning') } %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>

            <tfoot>
              <tr role="row">
                <th><%= t('activerecord.attributes.institutions.name') %></th>
                <th><%= t('activerecord.attributes.institutions.institution_owner') %></th>
                <th class="col-xs-1"><%= t('form.column.actions') %></th>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to t('button.new'), new_admin_institution_path, class: 'btn btn-success pull-right' %>
  </div>
</div>

app/views/admin/institutions/new.html.erb
<%= form_for @institution, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="box-title">New Institution</h3>
        </div>

        <div class="panel-body">
          <%= render partial: 'admin/institutions/form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to t('button.cancel'), admin_institutions_path, class: 'btn btn-danger' %>
          <%= f.submit t('button.submit'), class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/institutions/show.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-default">

			<div class="panel-heading">
				<h3 class="box-title"><%= t('admin.institutions.index.title') %></h3>
			</div>

			<div class="panel-body">
				<p>
					<strong><%= t('activerecord.attributes.institutions.name') %>:</strong>
					<%= @institution.name %>
				</p>

				<p>
					<strong><%= t('activerecord.attributes.institutions.institution_owner') %>:</strong>
					<%# @institution.institution_owner.email %>
				</p>

				<%= link_to raw('<i class="fa fa-pencil"></i>'), edit_owner_student_path(@institution), class: 'btn btn-sm btn-warning' %>

				<%= link_to raw('<i class="fa fa-trash"></i>'), owner_student_path(@institution), class: 'btn btn-sm btn-danger', method: :delete,
                                            data: { confirm: t('admin.institutions.destroy.warning') } %>
			</div>

			<div class="box-footer">
				<%= link_to t('button.back'), owner_students_path, class: 'btn btn-success' %>
			</div>

		</div>
	</div>
</div>