config/routes.rb
Rails.application.routes.draw do
  # Back admin routes start


  namespace :owner do
    root to: 'subscriptions#index'
    resources :students
    resources :asignatures
    resources :subscriptions
    resources :fees
    get '/dashboard', to: 'dashboard#index'
    get '/generate_fees/:month/:year', to: 'fees#generate_fees', as: 'generate_fees'
    get '/pay_fee/:id/:fee_id', to: 'fees#pay_fee', as: 'pay_fee'
  end

  namespace :admin do
    root to: 'dashboard#index'
    resources :users
    resources :institutions
    get '/send_promotion_email', to: 'dashboard#send_promotion_email', as: 'send_promotion_email'
    get '/edit_password/:id', to: 'users#edit_password', as: 'user_edit_password'
  end

  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  # Application root
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # Front routes end
end

app/models/user.rb
class User < ApplicationRecord
  ROLES = %w[admin institution_owner secretary teacher student student_tutor].freeze

  belongs_to :institution_owner
  belongs_to :student
  #belongs_to :teacher
  #belongs_to :secretary
  #belongs_to :student_tutor

  validates :name, presence: true
  validates :email, uniqueness: true, email: true



  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end
  
  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def is?(role)
    roles.include?(role.to_s)
  end

  def admin!
    self.roles = self.roles + ['admin']
  end

  def institution_owner!(institution)
    self.roles = self.roles + ['institution_owner']
    self.institution_owner = InstitutionOwner.create!(institution_id: institution.id)
  end

  def student!
    self.roles = self.roles + ['student']
  end

  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::BaseController
    respond_to :json, :html
    before_action :set_user, only: [:show, :edit, :edit_password, :update, :destroy]

    # GET /users
    def index
      @users = User.all
    end

    # GET /users/1
    def show
    end

    # GET /users/new
    def new
      @user = User.new
      @url = admin_users_path
    end

    # GET /users/1/edit
    def edit
      @url = admin_user_path(@user)
    end

    # GET /edit_password/:id
    def edit_password
      @url = admin_user_path(@user)
    end

    # POST /users
    def create
      @user = User.new(user_params)
      if @user.save
        add_roles_profiles(user_params[:roles])
        flash[:notice] = t('admin.users.create.success')
        redirect_to admin_users_path
      else
        flash[:warning] = @user.errors.full_messages.uniq.join(', ')
        respond_with :new, :admin, :user
      end
    end

    # PATCH/PUT /users/1
    def update
      if @user.update(user_params)
        #add_roles_profiles(user_params[:roles])
        flash[:notice] = t('admin.users.update.success')
        redirect_to admin_users_path
      else
        flash[:warning] = @user.errors.full_messages.uniq.join(', ')
        respond_with :edit, :admin, :user
      end
    end

    # DELETE /users/1
    def destroy
      @user.destroy
      respond_to do |format|
        format.html { redirect_to admin_users_path, notice: t('admin.users.destroy.success') }
      end
    end

    private 
      def set_user
        @user = User.find(params[:id])
      end

      def user_params
        params.require(:user).permit(:email, :password, :password_confirmation, :name, roles: [])
      end

      def add_roles_profiles(roles)
        roles.each do |role|
          @user.institution_owner = InstitutionOwner.find_or_create_by!(user_id: @user.id) if role == "institution_owner"
        end if roles
      end
  end
end

app/views/admin/users/_edit_form.html.erb
<div class="form-group">
  <%= f.label t('activerecord.attributes.user.email') %>
  <%= f.email_field :email, class: "form-control", placeholder: "Enter email", required: true %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

<div class="form-group">
  <%= f.label t('activerecord.attributes.user.name') %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter name", required: true %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

<!--
<div class="form-group">
  <h3><%= t('activerecord.attributes.user.roles_mask') %></h3>
  <%# for role in User::ROLES %>
    <%# check_box_tag "user[roles][#{role}]", role, @user.roles.include?(role), {:name => "user[roles][]"}%>
    <%# label_tag "user_roles_#{role}", role.humanize %><br />
  <%# end %>
  <%# hidden_field_tag "user[roles][]", "" %>
</div>
-->

app/views/admin/users/_edit_password_form.html.erb
<div class="form-group">
  <%= f.label t('activerecord.attributes.user.password') %>
  <%= f.password_field :password, class: "form-control", required: true %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

<div class="form-group">
  <%= f.label t('activerecord.attributes.user.repeat_password') %>
  <%= f.password_field :password_confirmation, class: "form-control", required: true %>
  <span class="help-block"><i>* <%= t('validation.required_field')%> </i><span>
</div>

app/views/admin/users/_new_form.html.erb
<div class="form-group">
  <%= f.label t('activerecord.attributes.user.name') %>
  <%= f.text_field :name, class: "form-control", placeholder: "Enter name", required: true %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

<div class="form-group">
  <%= f.label t('activerecord.attributes.user.email') %>
  <%= f.email_field :email, class: "form-control", placeholder: "Enter email", required: true %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

<div class="form-group">
  <%= f.label t('activerecord.attributes.user.password') %>
  <%= f.password_field :password, class: "form-control", required: true %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

<div class="form-group">
  <%= f.label t('activerecord.attributes.user.repeat_password') %>
  <%= f.password_field :password_confirmation, class: "form-control", required: true %>
  <span class="help-block"><i>* <%= t('validation.required_field')%></i><span>
</div>

<!--
<div class="form-group">
  <h3><%= t('activerecord.attributes.user.roles_mask') %></h3>
  <%# for role in User::ROLES %>
    <%# check_box_tag "user[roles][#{role}]", role, @user.roles.include?(role), {:name => "user[roles][]"}%>
    <%# label_tag "user_roles_#{role}", role.humanize %><br />
  <%# end %>
  <%# hidden_field_tag "user[roles][]", "" %>
</div>
-->

app/views/admin/users/edit.html.erb
<%= form_for @user, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="box-title"><%= t('admin.users.edit.title') %></h3>
        </div>

        <div class="panel-body">
          <%= render partial: 'admin/users/edit_form', locals: { f: f } %>
          <%= link_to 'Edit Password', admin_user_edit_password_path, class: 'btn btn-warning' %>
        </div>

        <div class="box-footer">
          <%= link_to t('button.cancel'), admin_users_path, class: 'btn btn-danger' %>
          <%= f.submit t('button.submit'), class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/users/edit_password.html.erb
<%= form_for @user, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="box-title">Edit User</h3>
        </div>

        <div class="panel-body">
          <%= render partial: 'admin/users/edit_password_form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to t('button.cancel'), admin_users_path, class: 'btn btn-danger' %>
          <%= f.submit t('button.submit'), class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h3 class="box-title"><%= t('admin.users.index.title') %></h3>
      </div>

      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-bordered table-striped" role="grid">
            <thead>
              <tr>
                <th><%= t('activerecord.attributes.users.name') %></th>
                <th class="hidden-xs"><%= t('activerecord.attributes.users.email') %></th>
                <th class="col-xs-1"><%= t('form.column.actions') %></th>
              </tr>
            </thead>

            <tbody>
              <% @users.each do |user| %>
              <tr>
                <td> <%= user.name %> </td>
                <td class="hidden-xs"> <%= user.email %> </td>
                <td>
                  <div class="btn-row">
                  <%= link_to raw('<i class="fa fa-eye"></i>'), admin_user_url(user), class: 'btn btn-sm btn-success' %>
                    <%= link_to raw('<i class="fa fa-pencil"></i>'), edit_admin_user_url(user), class: 'btn btn-sm btn-warning' %>
                    <%= link_to raw('<i class="fa fa-trash"></i>'), admin_user_url(user), class: 'btn btn-sm btn-danger', method: :delete,
                    data: { confirm: t('admin.users.destroy.warning') } %>
                  </div>
                </td>
              </tr>
              <% end %>
            </tbody>

            <tfoot>
              <tr role="row">
                <th><%= t('activerecord.attributes.users.name') %></th>
                <th class="hidden-xs"><%= t('activerecord.attributes.users.email') %></th>
                <th class="col-xs-1"><%= t('form.column.actions') %></th>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to t('button.new'), new_admin_user_path, class: 'btn btn-success pull-right' %>
  </div>
</div>

app/views/admin/users/new.html.erb
<%= form_for @user, url: @url, role: :form, html: { multipart: true } do |f| %>
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-default">

        <div class="panel-heading">
          <h3 class="box-title"><%= t('admin.users.new.title') %></h3>
        </div>

        <div class="panel-body">
          <%= render partial: 'admin/users/new_form', locals: { f: f } %>
        </div>

        <div class="box-footer">
          <%= link_to t('button.cancel'), admin_users_path, class: 'btn btn-danger' %>
          <%= f.submit t('button.submit'), class: "btn btn-success" %>
        </div>

      </div>
    </div>
  </div>
<% end %>

app/views/admin/users/show.html.erb
<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-default">

			<div class="panel-heading">
				<h3 class="box-title"><%= t('admin.users.index.title') %></h3>
			</div>

			<div class="panel-body">
				<p>
					<strong><%= t('activerecord.attributes.users.name') %>:</strong>
					<%= @user.name %>
				</p>

				<p>
					<strong><%= t('activerecord.attributes.users.email') %>:</strong>
					<%= @user.email %>
				</p>

				<p>
					<strong><%= t('activerecord.attributes.roles.name') %>:</strong>
					<%= "Admin" if @user.is? :admin %>
					<%= "Institution Owner" if @user.is? :instituon_admin %>
					<%= "Student" if @user.is? :student %>
				</p>

				<%= link_to raw('<i class="fa fa-pencil"></i>'), edit_admin_user_url(@user), class: 'btn btn-sm btn-warning' %>

				<%= link_to raw('<i class="fa fa-trash"></i>'), admin_user_url(@user), class: 'btn btn-sm btn-danger', method: :delete,
                                            data: { confirm: t('admin.users.destroy.warning')} %>
			</div>
				
			<div class="box-footer">
				<%= link_to t('button.back'), admin_users_path, class: 'btn btn-success' %>
			</div>

		</div>
	</div>
</div>