config/routes.rb
Rails.application.routes.draw do
  # Back admin routes start


  namespace :owner do
    root to: 'subscriptions#index'
    resources :students
    resources :asignatures
    resources :subscriptions
    resources :fees
    get '/dashboard', to: 'dashboard#index'
    get '/generate_fees/:month/:year', to: 'fees#generate_fees', as: 'generate_fees'
    get '/pay_fee/:id/:fee_id', to: 'fees#pay_fee', as: 'pay_fee'
  end

  namespace :admin do
    root to: 'dashboard#index'
    resources :users
    resources :institutions
    get '/send_promotion_email', to: 'dashboard#send_promotion_email', as: 'send_promotion_email'
    get '/edit_password/:id', to: 'users#edit_password', as: 'user_edit_password'
  end

  # Back admin routes end

  # Front routes start
  devise_for :users, only: [:session, :registration], path: 'session',
             path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }


  # Application root
  devise_scope :user do
    root to: "devise/sessions#new"
  end
  # Front routes end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.is? :admin
      can :manage, User
    end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asignature.rb
class Asignature < ApplicationRecord
  belongs_to :institution
end

app/models/classroom.rb
class Classroom < ApplicationRecord
	belongs_to :institution
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/contact_information.rb
class ContactInformation < ApplicationRecord
	belongs_to :student
end

app/models/day.rb
class Day < ApplicationRecord
end

app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || 'is not a valid email')
    end
  end
end

app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :student
  has_many :items

  enum status: [:pending, :payed, :partially_paid, :cancelled]
end

app/models/hour.rb
class Hour < ApplicationRecord
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :institution_owners
  has_many :students, dependent: :delete_all
  
  validates :name, presence: true
end

app/models/institution_owner.rb
class InstitutionOwner < ApplicationRecord
  belongs_to :institution
  has_one :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :subscription
  belongs_to :fee
end

app/models/student.rb
class Student < ApplicationRecord
  has_one :user
  belongs_to :institution

  has_many :subscriptions
  accepts_nested_attributes_for :subscriptions, :allow_destroy => true

  has_many :contact_informations
  accepts_nested_attributes_for :contact_informations, :allow_destroy => true

  has_many :fees

  scope :actives, -> { where(status: 1) }

  def full_name
    "#{self.name} #{self.last_name}"
  end

  def pay_pending?
    self.fees.where('fees.status = 0').count > 0
  end

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :student
  belongs_to :asignature, required: true
  belongs_to :day, required: true
  belongs_to :start_at, foreign_key: "start_at_id", class_name: "Hour", required: true
  belongs_to :end_at, foreign_key: "end_at_id", class_name: "Hour", required: true
  belongs_to :classroom, required: true

  enum charging_mode: [:monthly, :per_class]
  
  scope :actives, -> { where(status: 1) }

  def description
    self.asignature.name + " | " + self.day.name + " de " + self.start_at.str_time + " a " + self.end_at.str_time 
  end

end

app/models/user.rb
class User < ApplicationRecord
  ROLES = %w[admin institution_owner secretary teacher student student_tutor].freeze

  belongs_to :institution_owner
  belongs_to :student
  #belongs_to :teacher
  #belongs_to :secretary
  #belongs_to :student_tutor

  validates :name, presence: true
  validates :email, uniqueness: true, email: true



  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end
  
  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero?
    end
  end

  def is?(role)
    roles.include?(role.to_s)
  end

  def admin!
    self.roles = self.roles + ['admin']
  end

  def institution_owner!(institution)
    self.roles = self.roles + ['institution_owner']
    self.institution_owner = InstitutionOwner.create!(institution_id: institution.id)
  end

  def student!
    self.roles = self.roles + ['student']
  end

  # Include default devise modules. Others available are:
  # :registerable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
module Admin
  class BaseController < ApplicationController
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
    before_action :verify_admin

    layout :layout_by_resource

    def index
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:password, :password_confirmation, :current_password, :name, roles: [])
      end
    end

    private 
    
      def layout_by_resource
        if devise_controller?
          'layouts/devise'
        else
          'admin/layouts/admin'
        end
      end
      
      def verify_admin
        raise CanCan::AccessDenied unless current_user.is?(:admin)
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    return admin_users_path if user.is?(:admin)
    return owner_root_path if user.is?(:institution_owner)
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def dashboard_url
		return new_user_session_url unless current_user
		return owner_dashboard_path if current_user.is? :admin
		return owner_dashboard_path if current_user.is? :institution_owner
		return new_user_session_url
	end

	def number_to_month (n)
		month = "Enero" if n == 1
		month = "Febrero" if n == 2
		month = "Marzo" if n == 3
		month = "Abril" if n == 4
		month = "Mayo" if n == 5
		month = "Junio" if n == 6
		month = "Julio" if n == 7
		month = "Agosto" if n == 8
		month = "Septiembre" if n == 9
		month = "Octubre" if n == 10
		month = "Noviembre" if n == 11
		month = "Diciembre" if n == 12
  
		month
	end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/admin/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no, minimal-ui"/>
    <meta name="keywords" content="" />
    <meta name="title" content="<%= content_for?(:title) ? yield(:title) : Rails.application.secrets[:site_title] %>">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : Rails.application.secrets[:site_title] %>">
    <title><%= content_for?(:title) ? yield(:title) : Rails.application.secrets[:site_title] %></title>

    <%= stylesheet_link_tag 'application_back', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">

    <div class="wrapper">
      <%= render partial: 'admin/shared/header' %>
      <%= render partial: 'admin/shared/sidebar' %>
      <div class="content-wrapper">
        <%# render partial: 'admin/shared/content_header' #%>
        <section class="content">
          <%= render partial: 'admin/shared/messages' %>
          <%= yield %>
        </section>
      </div>
      <%= render partial: 'admin/shared/footer' %>
    </div>
  </body>

  <%= javascript_include_tag 'application_back' %>

  <% if content_for?(:added_scripts) %>
    <%= yield :added_scripts %>
  <% end %>
</html>

app/views/admin/shared/_content_header.html.erb
<section class="content-header">
  <h1> <%= params[:controller].split('/').last.humanize %> </h1>
  <ol class="breadcrumb">
    <li><%= link_to '<i class="fa fa-dashboard"></i> Home'.html_safe, admin_root_path %></li>
    <li class="active"> <%= params[:controller].split('/').last.humanize %> </li>
  </ol>
</section>

app/views/admin/shared/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
  </div>
</footer>

app/views/admin/shared/_header.html.erb
<header class="main-header">
  <%= content_tag :a, href: admin_root_path, class: 'logo' do %>
    <span class="logo-mini">
    <b>A</b>T</span>
    <span class="logo-lg">
    <b><%= Rails.application.secrets[:site_title] %></b></span>
  <% end %>

  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only"><%= t('header.toogle_navigation') %></span>
    </a>

    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li class="dropdown user user-menu">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "http://placehold.it/160x160", class: "user-image" %>
            <span class="hidden-xs"><%= current_user.name %></span>
          </a>
          <ul class="dropdown-menu">
            <li class="user-header">
              <%= image_tag "http://placehold.it/160x160", class: "img-circle" %>

              <p>
                <%= current_user.name %>
                <small><%= t('header.member_since') %> <%= current_user.created_at.strftime("%B, %Y") %></small>
              </p>
            </li>

            <li class="user-footer">
              <div class="pull-left">
                <%= link_to t('header.profile'), edit_admin_user_path(current_user), class: 'btn btn-default -btn-flat' %>
              </div>
              <div class="pull-right">
                <%= link_to t('header.sign_out'), destroy_user_session_path, method: :delete, class: 'btn btn-default btn-flat' %>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/admin/shared/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <h4>
        <i class="icon fa fa-<%= name.to_s == 'notice' ? 'check' : 'ban' %>"></i> 
        <%= name.to_s == 'notice' ? t('validation.success') : t('validation.warning') %>
      </h4>
      <%= content_tag :div, raw(msg.split(",").join("<br>").html_safe), :id => "flash_#{name}" %>
    </div>
    <% flash[name] = nil %>
  <% end %>
<% end %>

app/views/admin/shared/_sidebar.html.erb
<aside class="main-sidebar">
  <section class="sidebar">

    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag "http://placehold.it/160x160", class: "img-circle" %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>
        <%= link_to '<i class="fa fa-circle text-success"></i><span>Online</span>'.html_safe, admin_root_path %>
      </div>
    </div>

    <ul class="sidebar-menu">
      <li class="header"><%= t('admin.sidebar.main_navigation') %></li>
    
      <% if current_user.is? :institution_owner %>
      <li> <%= link_to '<i class="fa fa-dashboard"></i><span>Administración</span>'.html_safe, owner_dashboard_path %> </li>
      <% end %>

      <% if current_user.is? :institution_owner %>
      <!-- Calendario de estudiantes -->
      <li><%= link_to '<i class="fa fa-calendar"></i> Calendario de estudiantes'.html_safe, owner_subscriptions_path %></li>

      <!-- Asignaturas -->
      <li> <%= link_to '<i class="fa fa-circle-o"></i> Asignaturas'.html_safe, owner_asignatures_path %> </li>
      <% end %>

      <% if current_user.is? :admin %>
      <li class="header"><%= t('admin.sidebar.administration') %></li>
      <!-- Users -->
      <li class="treeview">
        <a href="#">
          <i class="fa fa-users"></i>
          <span><%= t('admin.users.title') %></span>
          <span class="pull-right-container">
            <i class="fa fa-angle-left pull-right"></i>
          </span>
        </a>
        <ul class="treeview-menu">
          <li> <%= link_to '<i class="fa fa-circle-o"></i> List Users'.html_safe, admin_users_path %> </li>
          <li> <%= link_to '<i class="fa fa-circle-o"></i> Create User'.html_safe, new_admin_user_path %> </li>
        </ul>
      </li>
      <% end %>

    </ul>

  </section>
</aside>

app/views/shared/_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p></p>
  </div>
</div>

app/views/shared/_navigation.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= t('navigation.main_title') %></h3>
    <nav>
      <ul class="nav masthead-nav">
        <li> <%= link_to t('navigation.root'), root_path %> </li>
        <li> <%= link_to t('navigation.admin'), dashboard_url %> </li>
      </ul>
    </nav>
  </div>
</div>